name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run build -- --base /pawprintsrescue/
        env:
          VITE_ASM_SERVICEURL: ${{ secrets.VITE_ASM_SERVICEURL }}
          VITE_ASM_ACCOUNT: ${{ secrets.VITE_ASM_ACCOUNT }}
          VITE_ASM_USERNAME: ${{ secrets.VITE_ASM_USERNAME }}
          VITE_ASM_PASSWORD: ${{ secrets.VITE_ASM_PASSWORD }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: dist
